name: medjargone
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - numpy
  - pandas
  - datasets
  - transformers
  - tokenizers
  - safetensors
  - tqdm
  - regex
  - pyyaml
  - pip
  - pip:
      - evaluate
      - rouge_score
      - nltk
      - accelerate
