"""

Use an LLM on pipeline summaries to extract jargon and save the rewritten texts to JSON.

Usage:
    python generate_rewrites.py --model path/to/model/ --pipeline_file results/outputs/outputs.json --output results/outputs/rewritten_outputs.json --max_model_len 8192

"""

import vllm
import argparse
import json
import pandas as pd

def main():
    # add optional command-line args to add a soft limit to the length of the generated summary
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", required=True, help="Path to HuggingFace Transformers model to run inference with")
    parser.add_argument("--pipeline_file", required=True, help="Path to inference outputs generated by *BART + MedJEx pipeline (default: outputs.json)")
    parser.add_argument("--output", default="rewritten_outputs.json", help="Path to save inference outputs (default: rewritten_outputs.json)")
    parser.add_argument("--max-model-len", type=int, default=8192, help="Max context length in tokens; reduce if OOM (default: 8192)")
    args = parser.parse_args()

    # read prompt template (plain instructions; no chat-format wrappers)
    print("Reading prompt template...")
    with open("./rewrite_prompt.txt", "r", encoding="utf-8") as prompt_file:
        system_prompt = prompt_file.read()

    # combine the template with the pipeline texts to create prompts
    print(f"Loading pipeline summaries...")
    with open(args.pipeline_file, "r") as f:
        data = json.load(f)
    
    examples = [ex for ex in data["examples"]]
    pipeline_texts = [ex["pred"] for ex in examples]
    jargon_lists = [[entry["text"] for entry in row] for row in examples["mlm-scores"]]

    # create an LLM
    # max_model_len caps context to avoid OOM on 11 GB 2080 Ti
    # (Qwen3.5's native context is 262k which would OOM immediately)
    print(f"Loading model: {args.model}...")
    llm = vllm.LLM(
        model=args.model,
        dtype="float16",
        gpu_memory_utilization=0.90,
        max_model_len=args.max_model_len,
    )

    # Recommended sampling params for Qwen3.5 non-thinking mode (text tasks)
    sampling_params = vllm.SamplingParams(
        temperature=1.0,
        top_p=1.0,
        top_k=20,
        presence_penalty=2.0,
        max_tokens=512,
    )

    # Build one conversation per example; llm.chat() applies the model's
    # chat template automatically (Qwen uses <|im_start|> format, not [INST])
    conversations = [
        [
            {"role": "system", "content": system_prompt.replace("<<jargon_list>>", jl)},
            {"role": "user", "content": original},
        ]
        for original, jl in zip(pipeline_texts, jargon_lists)
    ]

    # generate texts from the prompts
    print(f"Generating rewrites on {len(pipeline_texts)} examples...\n")
    outputs = llm.chat(conversations, sampling_params)

    # build results
    results = []
    for i, (text, output) in enumerate(zip(pipeline_texts, outputs)):
        results.append({
            "id": i,
            "input": text,
            "pred": output.outputs[0].text, # get generated text only
        })

        if (i + 1) % 50 == 0:
            print(f"  {i + 1}/{len(pipeline_texts)} done.")

    # write to final outputs json
    with open(args.output, "w") as f:
        json.dump({
            "model": args.model,
            "examples": results
        }, f, indent=2)

    print(f"\nSaved {len(results)} examples to {args.output}.")

if __name__ == "__main__":
    main()