name: medjargone-gpu
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.10
  - pip
  - pip:
    - --index-url https://download.pytorch.org/whl/cu118
    - --extra-index-url https://pypi.org/simple
    - torch>=2.0
    - numpy==1.26.4
    - pyarrow==6.0.0
    - pyarrow-hotfix==0.7
    - datasets==2.8.0
    - fsspec==2023.9.2
    - huggingface-hub==0.17.0
    - transformers==4.35.2
    - tokenizers==0.15.2
    - accelerate==0.31.0
    - peft
    - evaluate==0.4.2
    - rouge-score==0.1.2
    - nltk==3.9.1
    - bert-score==0.3.13
    - safetensors==0.5.3
    - multiprocess==0.70.14
    - dill==0.3.6
    - xxhash==3.5.0
    - pandas==2.2.3
    - tqdm==4.67.1
    - regex==2024.11.6
    - pyyaml==6.0.2
    - matplotlib==3.10.3
    - textstat
